apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tify-redis-data
  namespace: tify
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
