apiVersion: v1
kind: Service
metadata:
  name: tify-backend
  namespace: tify
  labels:
    app: tify-backend
spec:
  type: ClusterIP
  selector:
    app: tify-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
