apiVersion: v1
kind: Service
metadata:
  name: tify-frontend
  namespace: tify
  labels:
    app: tify-frontend
spec:
  type: NodePort
  selector:
    app: tify-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
      protocol: TCP
