apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tify
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: tify-backend
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - tify-backend:8081   # Actuator 独立端口，不走 Nginx
        relabel_configs:
          - target_label: application
            replacement: tify
