apiVersion: v1
kind: Service
metadata:
  name: tify-pgvector
  namespace: tify
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: tify-pgvector
