apiVersion: v1
kind: Service
metadata:
  name: hify-pgvector
  namespace: hify
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: hify-pgvector
