apiVersion: v1
kind: Secret
metadata:
  name: hify-mysql-secret
  namespace: hify
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "hify_root_pw"
  MYSQL_DATABASE: "hify"
  MYSQL_USER: "hify"
  MYSQL_PASSWORD: "hify_pw"
